---
title: "사회연결망분석SNA"
author: "이성령"
date: "2017년 7월 21일"
output: rmarkdown::github_document
---
SNA -> 통계 
IGRAPH 복잡한 문제 해결 -> GRAPH
구성요소 
방향그래프와 무방향 그래프  VERTEX LINK EDGE NODE
그래프생성 PLOT()
유형별조회  get.edge.attributes
방향제거 
그래프 출력 write.graph
표현방법 1.집합론적 관계쌍으로 표현 2.matrix 인접행렬로 표
Degree  노드에 연결된 링크의 수를 밀도 혹은 
```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "README_figs/README-"
)
```

```{r}

library(igraph)
ga.data <- read.csv(choose.files())
g<-graph.data.frame(ga.data,directed=FALSE) # 비방향성
plot(g)
#V(g)$label <- NA # VERTEX(정점) EDGE(가지) -> 버텍스 정보에 접근가능
V(g)$size <- degree(g)*5 #차수
hist(degree(g)) 
sort(degree(g),decreasing = T)
df_deg <- as.data.frame(table(degree(g)))
colnames(df_deg) <- c("degree","count")
write.csv(df_deg,file="degree_dist.csv")
plot(g)
degree(g)
sum(degree(g))
degree(g,mode="total")
degree(g,mode="in")
degree(g,mode="out")
vcount(g) # 전체 vertex가 몇개인가. 동그라미 숫자 
ecount(g) # 가지 수 
# 부족한 감이 있다. 근접중심성을 나타낼 수 있게 플랏을 수정해 보겠습니다.
```
#근접중심
```{r}
clo <- closeness(g) 
#1을 더하는 이유는 min 근접중심성은 0이 되기때문에, 자연수로 만들어 주기 위해)
clo.score <- round((clo-min(clo))*length(clo)/max(clo))+1
# rev는 벡터의 순서를 거꾸로(reverse) 해줌 : 중심성이 높을수록 진한색으로 할당
clo.colors <- rev(heat.colors(max(clo.score))) #연한색에서 찐한색
V(g)$color <- clo.colors[clo.score]
plot(g)
# 그래프로부터 다시 인접행렬로 바꿀 수 있다.
mat <- as.matrix(get.adjacency(g))

```
